# 激活的环境
spring:
  profiles:
    active: dev
  config:
    import: classpath:project.yml
    encoding: UTF-8
  jackson:
    time-zone: Asia/Shanghai
    serialization:
      write-dates-as-timestamps: false

# 安全设置
security:
    whitelist-urls:
      - /swagger-ui/**
      - /swagger-ui.html
      - /v3/api-docs/**
      - /favicon.ico
      - /common/**
      - /auth/**
    login-only-urls:
      - /sys/profile
      - /sys/password

# JWT 配置
jwt:
  secret: xusheng-secret-key-please-change-to-strong-key
  expire-days: 3